package org.fhw.asta.kasse.shared.model;

import java.io.Serializable;

/**
 * Container to represent an accounting category stored in DB. An accounting
 * category can be a party or regular script sell. In general, such a category
 * represents an occasion or event, on which articles are sold.
 * 
 * @author Julian Wefers
 */
public class AccountingCategory implements Serializable
{
  private static final long serialVersionUID = 1L;

  /** Category id, automatically generated by DB. */
  private int id;

  /** Category name, e.g. "Sommerfest" or "Skriptverkauf". */
  private String name;

  /**
   * Creates a new Object representation of a certain accounting category.
   * Sdould come straight from DB access.
   * 
   * @param id
   *          category id
   * @param name
   *          category name
   */
  public AccountingCategory(final int id, final String name)
  {
    this.id = id;
    this.name = name;
  }

  /**
   * Default constructor, only needed for Serialisation. Will create an empty
   * Category. Don't use!
   */
  public AccountingCategory()
  {
  }

  /**
   * Returns the category id.
   * 
   * @return accounting category id
   */
  public int getId()
  {
    return this.id;
  }

  /**
   * Returns the category name.
   * 
   * @return accounting category name
   */
  public String getName()
  {
    return this.name;
  }
}
