package org.fhw.asta.kasse.shared.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Container to represent a specific bill OR order stored in DB. Bills and order
 * are stored in the same way, because any order will eventually result in a
 * bill with the same structure. This Difference is determined by it's order
 * state. If the order state is "fetched", the Object represents a bill. A
 * BillOrder alway has an issuer and a receipient. It can be cancelled which
 * should make it invalid for company reports.
 * 
 * @author Julian Wefers
 */
public class BillOrder implements Serializable
{
  private static final long serialVersionUID = 1L;

  /** Bill ID, generated by DB */
  private int id;

  /** receipient/customer */
  private Person receipient;

  /** issuer/employee who took the order */
  private Person issuer;

  /** Date and time of creation */
  private Date creationDate;

  /** Flag, whether the customer paid cash */
  private boolean paidCash;

  /** State of the order, if it is fetched, this object is considered a bill */
  private OrderState state;
  


private int discount;

  /**
   * If an order is cancelled, any service granted has been revoked, thus this
   * Order is invalid for company reports
   */
  private boolean cancelled;

  /**
   * Creates an Object representation of a specific BillOrder. Values may not ne
   * changed after they have been set here.
   * 
   * @param id
   * @param receipient
   * @param issuer
   * @param creationDate
   * @param paidCash
   * @param state
   * @param cancelled
   * @param articles
   */
  public BillOrder(final int id, final Person receipient, final Person issuer,
      final Date creationDate, final boolean paidCash, final OrderState state,
      final boolean cancelled, final int discount)
  {
    this.id = id;
    this.receipient = receipient;
    this.issuer = issuer;
    this.creationDate = creationDate;
    this.paidCash = paidCash;
    this.state = state;
    this.cancelled = cancelled;
    this.discount = discount;
  }

  public BillOrder()
  {
  }

  public int getId()
  {
    return this.id;
  }
  
  public int getDiscount() {
	return discount;
  }

  public Person getIssuer()
  {
    return this.issuer;
  }

  public Person getReceipient()
  {
    return this.receipient;
  }

  public Date getCreationDate()
  {
    return this.creationDate;
  }

  public boolean paidCash()
  {
    return this.paidCash;
  }

  public OrderState getState()
  {
    return this.state;
  }

  public boolean isCancelled()
  {
    return this.cancelled;
  }

  public void setCancelled(final boolean cancelled)
  {
    this.cancelled = cancelled;
  }

  public boolean isBill()
  {
    return this.state == OrderState.Fetched;
  }

  public boolean isOrder()
  {
    return !this.isBill();
  }
}
